name: 'Hostloc Auto Get Points'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 17 * * *'

jobs:
  get_points:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install dependencies'
      run: pip install requests
           pip install pyaes
           pip install rsa
           pip install hashlib
           pip install base64
    - name: 'Get points'
      env:
        HOSTLOC_USERNAME: ${{ secrets.HOSTLOC_USERNAME }}
        HOSTLOC_PASSWORD: ${{ secrets.HOSTLOC_PASSWORD }}
      run: python hostloc.py
      
      
